version: "2.1"
services:
  dropshipr:
    build: .
    ports:
      - 3000:3000 # expose ports - HOST:CONTAINER
      - 35729:35729
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - e:/github.com/radityasurya/dropshipr/src:/usr/src/app/src
      - /usr/src/app/node_modules
